/**
 * This script generates certificate data from:
 * - public/certificate/ directory (PDF files)
 * - public/links.json (verification URLs)
 *
 * Run with: npx tsx scripts/generate-certificates.ts
 */

import { promises as fs } from "fs";
import { join } from "path";

interface CertificateData {
  name: string;
  pdfPath: string;
  verifyUrl: string;
  issuer?: string;
  date?: string;
}

async function generateCertificates() {
  const certificateDir = join(process.cwd(), "public", "certificate");
  const linksPath = join(process.cwd(), "public", "links.json");

  // Read all PDF files from certificate directory
  const files = await fs.readdir(certificateDir);
  const pdfFiles = files.filter((file) => file.toLowerCase().endsWith(".pdf"));

  // Read verification URLs
  const linksContent = await fs.readFile(linksPath, "utf-8");
  const links: Record<string, string> = JSON.parse(linksContent);

  // Match PDFs with verification URLs
  const certificates: CertificateData[] = [];

  for (const pdfFile of pdfFiles) {
    // Remove .pdf extension to get the certificate name
    const name = pdfFile.replace(/\.pdf$/i, "");
    const pdfPath = `/certificate/${pdfFile}`;

    // Find matching verification URL
    let verifyUrl = "";

    // Try to find exact match first
    if (links[name]) {
      verifyUrl = links[name].split("?")[0]; // Clean URL
    } else {
      // Try partial match
      for (const [linkName, url] of Object.entries(links)) {
        if (name.toLowerCase().includes(linkName.toLowerCase()) ||
            linkName.toLowerCase().includes(name.toLowerCase())) {
          verifyUrl = url.split("?")[0];
          break;
        }
      }
    }

    // Extract issuer and date from name
    const issuer = extractIssuer(name);
    const date = extractDate(name);

    certificates.push({
      name,
      pdfPath,
      verifyUrl,
      issuer,
      date,
    });
  }

  // Output as TypeScript module
  const output = `// Auto-generated by scripts/generate-certificates.ts
// Do not edit manually - regenerate using: npx tsx scripts/generate-certificates.ts

export const certificates: CertificateData[] = ${JSON.stringify(certificates, null, 2)};
`;

  const outputPath = join(process.cwd(), "src", "data", "certificates.ts");
  await fs.mkdir(join(process.cwd(), "src", "data"), { recursive: true });
  await fs.writeFile(outputPath, output);

  console.log(`Generated ${certificates.length} certificates to ${outputPath}`);
}

function extractIssuer(name: string): string {
  const issuers = ["DataCamp", "IKIU", "IBM", "Tableau", "Coursera", "Udemy", "edX"];
  for (const issuer of issuers) {
    if (name.toLowerCase().includes(issuer.toLowerCase())) {
      return issuer;
    }
  }
  return "Unknown";
}

function extractDate(name: string): string {
  const yearMatch = name.match(/\b(20\d{2})\b/);
  return yearMatch ? yearMatch[1] : new Date().getFullYear().toString();
}

generateCertificates().catch(console.error);